"""add runs.answer_ui

Revision ID: d2a378047698
Revises: ebf05a862e33
Create Date: 2026-08-05 00:25:23.182725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d2a378047698"
down_revision: str | None = "ebf05a862e33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs", sa.Column("answer_ui", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "answer_ui")
    # ### end Alembic commands ###
